package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

var (
	typeNames = flag.String("type", "", "comma-separated list of type names; must be set")
	out       = flag.String("out", "", "output file name; default srcdir/<type>_schema.go")
	pkgName   = flag.String("pkg", "schema", "output package name")
)

func Usage() {
	fmt.Fprintf(os.Stderr, "Usage of aggify-gen:\n")
	fmt.Fprintf(os.Stderr, "\taggify-gen -type T [flags]\n")
	flag.PrintDefaults()
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("aggify-gen: ")
	flag.Usage = Usage
	flag.Parse()

	if len(*typeNames) == 0 {
		flag.Usage()
		os.Exit(2)
	}

	typesList := strings.Split(*typeNames, ",")

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedImports | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		log.Fatal(err)
	}
	if len(pkgs) != 1 {
		log.Fatalf("error: %d packages found", len(pkgs))
	}
	pkg := pkgs[0]

	if len(pkg.Errors) > 0 {
		for _, err := range pkg.Errors {
			log.Println(err)
		}
		log.Fatalf("errors while loading package")
	}

	g := &Generator{
		pkg:   pkg,
		types: typesList,
	}
	g.generate()

	src := g.format()

	outFile := *out
	if outFile == "" {
		outFile = strings.ToLower(typesList[0]) + "_schema.go"
	}

	err = os.MkdirAll(filepath.Dir(outFile), 0755)
	if err != nil {
		log.Fatalf("failed to create directory: %v", err)
	}

	err = os.WriteFile(outFile, src, 0644)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
}

type Generator struct {
	buf   bytes.Buffer
	pkg   *packages.Package
	types []string
}

func (g *Generator) generate() {
	g.buf.WriteString("// Code generated by aggify-gen. DO NOT EDIT.\n")
	g.buf.WriteString("package " + *pkgName + "\n\n")

	for _, tName := range g.types {
		obj := g.pkg.Types.Scope().Lookup(tName)
		if obj == nil {
			log.Fatalf("type %s not found in package %s", tName, g.pkg.Name)
		}

		named, ok := obj.Type().(*types.Named)
		if !ok {
			log.Fatalf("type %s is not a named type", tName)
		}

		str, ok := named.Underlying().(*types.Struct)
		if !ok {
			log.Fatalf("type %s is not a struct", tName)
		}

		g.buf.WriteString(fmt.Sprintf("var %s = %s", tName, g.typeDef(str)))
		g.buf.WriteString(g.valueDef(str, ""))
		g.buf.WriteString("\n\n")
	}
}

func (g *Generator) format() []byte {
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		return g.buf.Bytes()
	}
	return src
}

func (g *Generator) typeDef(str *types.Struct) string {
	var b bytes.Buffer
	b.WriteString("struct {\n")
	for i := 0; i < str.NumFields(); i++ {
		f := str.Field(i)
		if !f.Exported() {
			continue
		}
		
		tag := str.Tag(i)
		bsonName := extractBsonName(tag, f.Name())
		if bsonName == "-" {
			continue
		}

		nestedStr := getStruct(f.Type())
		if nestedStr != nil {
			b.WriteString(fmt.Sprintf("\t%s %s\n", f.Name(), g.typeDef(nestedStr)))
		} else {
			b.WriteString(fmt.Sprintf("\t%s string\n", f.Name()))
		}
	}
	b.WriteString("}")
	return b.String()
}

func (g *Generator) valueDef(str *types.Struct, prefix string) string {
	var b bytes.Buffer
	b.WriteString("{\n")
	for i := 0; i < str.NumFields(); i++ {
		f := str.Field(i)
		if !f.Exported() {
			continue
		}
		
		tag := str.Tag(i)
		bsonName := extractBsonName(tag, f.Name())
		if bsonName == "-" {
			continue
		}

		path := bsonName
		if prefix != "" {
			path = prefix + "." + bsonName
		}

		nestedStr := getStruct(f.Type())
		if nestedStr != nil {
			b.WriteString(fmt.Sprintf("\t%s: %s%s,\n", f.Name(), g.typeDef(nestedStr), g.valueDef(nestedStr, path)))
		} else {
			b.WriteString(fmt.Sprintf("\t%s: %q,\n", f.Name(), path))
		}
	}
	b.WriteString("}")
	return b.String()
}

func extractBsonName(tag string, fieldName string) string {
	// Simple extraction of bson tag, e.g. `bson:"address,omitempty"` -> "address"
	if !strings.Contains(tag, "bson:\"") {
		return fieldName
	}

	start := strings.Index(tag, "bson:\"") + 6
	end := strings.Index(tag[start:], "\"")
	if end == -1 {
		return fieldName
	}

	bsonVal := tag[start : start+end]
	parts := strings.Split(bsonVal, ",")
	if parts[0] != "" {
		return parts[0]
	}
	return fieldName
}

func getStruct(t types.Type) *types.Struct {
	switch u := t.Underlying().(type) {
	case *types.Struct:
		return u
	case *types.Pointer:
		return getStruct(u.Elem())
	case *types.Slice:
		return getStruct(u.Elem())
	case *types.Array:
		return getStruct(u.Elem())
	}
	return nil
}
