// Code generated by aggify-gen. DO NOT EDIT.
package schema

var User = struct {
	ID        string
	Email     string
	Name      string
	Addresses struct {
		City    string
		ZipCode string
	}
	Pointer struct {
		City    string
		ZipCode string
	}
}{
	ID:    "_id",
	Email: "email",
	Name:  "name",
	Addresses: struct {
		City    string
		ZipCode string
	}{
		City:    "address.city",
		ZipCode: "address.zip",
	},
	Pointer: struct {
		City    string
		ZipCode string
	}{
		City:    "ptrAddr.city",
		ZipCode: "ptrAddr.zip",
	},
}

var Order = struct {
	ID    string
	Items struct {
		ProductID string
		Quantity  string
	}
}{
	ID: "_id",
	Items: struct {
		ProductID string
		Quantity  string
	}{
		ProductID: "items.productId",
		Quantity:  "items.quantity",
	},
}
